import type { Snapshot } from '../api/snapshot'

export const VCS_HEAD = '5313961a0c2f4e8b9d7a6c5b4e3f2a1b0c9d8e7f'

export const allPresent: Snapshot = {
  repoview_version: '0.1.0',
  project: { root: '/work/example', name: 'example' },
  sources: [
    {
      source_id: 'vcs',
      kind: 'Vcs',
      location: '.',
      availability: 'Present',
      tool: 'git',
      tool_path: '/usr/bin/git',
      tool_version: 'git version 2.51.0',
      diagnostic: null,
      summary: { branch: 'main', head: VCS_HEAD, dirty: 0 },
    },
    {
      source_id: 'plan',
      kind: 'Planning',
      location: '.engineering',
      availability: 'Present',
      tool: 'aep',
      tool_path: '/usr/local/bin/aep',
      tool_version: 'aep 9.9.9',
      diagnostic: null,
      summary: {},
    },
    {
      source_id: 'spec',
      kind: 'Specification',
      location: 'ess',
      availability: 'Present',
      tool: 'ess',
      tool_path: '/usr/local/bin/ess',
      tool_version: 'ess 0.52.0',
      diagnostic: null,
      summary: { roots: ['ess'] },
    },
    {
      source_id: 'quality',
      kind: 'Quality',
      location: '.',
      availability: 'Present',
      tool: 'codegate',
      tool_path: '/usr/local/bin/codegate',
      tool_version: null,
      diagnostic: null,
      summary: {},
    },
    {
      source_id: 'docs',
      kind: 'Documents',
      location: '.',
      availability: 'Present',
      tool: null,
      tool_path: null,
      tool_version: null,
      diagnostic: null,
      summary: { files: ['README.md', 'AGENTS.md'] },
    },
  ],
}

export const FAILED_DIAGNOSTIC = 'error: store is corrupt (exit 3)'

export const degraded: Snapshot = {
  repoview_version: '0.1.0',
  project: { root: '/work/degraded', name: 'degraded' },
  sources: [
    {
      source_id: 'vcs',
      kind: 'Vcs',
      location: '.',
      availability: 'Present',
      tool: 'git',
      tool_path: '/usr/bin/git',
      tool_version: 'git version 2.51.0',
      diagnostic: null,
      summary: { branch: 'feature/x', head: VCS_HEAD, dirty: 2 },
    },
    {
      source_id: 'plan',
      kind: 'Planning',
      location: '.engineering',
      availability: 'ToolMissing',
      tool: 'aep',
      tool_path: null,
      tool_version: null,
      diagnostic: 'aep not found on PATH',
      summary: {},
    },
    {
      source_id: 'spec',
      kind: 'Specification',
      location: 'ess',
      availability: 'Failed',
      tool: 'ess',
      tool_path: '/usr/local/bin/ess',
      tool_version: null,
      diagnostic: FAILED_DIAGNOSTIC,
      summary: {},
    },
    {
      source_id: 'quality',
      kind: 'Quality',
      location: '.',
      availability: 'Absent',
      tool: 'codegate',
      tool_path: null,
      tool_version: null,
      diagnostic: null,
      summary: {},
    },
    {
      source_id: 'docs',
      kind: 'Documents',
      location: '.',
      availability: 'Absent',
      tool: null,
      tool_path: null,
      tool_version: null,
      diagnostic: null,
      summary: {},
    },
  ],
}
